internal/helm/client.go
internal/helm/client_test.go
internal/helm/config.go

- make usage TLS for Tiller calls enabled configurable
https://github.com/kyma-project/kyma/issues/5239

Make tiller TLS enabled by configuration

---

Gopkg.lock
internal/broker/server.go

Related to [#5092](https://github.com/kyma-project/kyma/issues/5092)

Enable prometheus metrics endpoint

---

Makefile
test/integration/integration_test.go
test/integration/suite_test.go

- add integration tests which tests if the URL templating works and checks if it is possible to pass basic auth credentials
Solves: https://github.com/kyma-project/kyma/issues/5349

Templating IT test

---

README.md
charts/helm-broker/templates/deploy.yaml
charts/helm-broker/values.yaml
contrib/local-etcd-config.yaml
contrib/redis-binding.yaml
contrib/redis-instance.yaml
contrib/sample-addons.yaml
docs/run-local.md
internal/config/config.go
test/integration/suite_test.go

- improve main README.md file with description how to run the Helm-Broker
- remove unnecessary fields from the configs
Resolves: https://github.com/kyma-project/kyma/issues/5239

Improve docs

---

charts/helm-broker/templates/deploy.yaml
charts/helm-broker/templates/ssh-cfg.yaml
deploy/controller/Dockerfile
deploy/controller/start.sh

- adopt Dockerfile and add known_hosts to enable Git SSH protocol
Related: https://github.com/kyma-project/kyma/issues/5139

Git SSH support

---

charts/helm-broker/templates/deploy.yaml

- fix deploy.yaml file in the chart

Fix helm chart yaml file

---

charts/helm-broker/templates/deploy.yaml
charts/helm-broker/templates/rbac.yaml
charts/helm-broker/values.yaml
config/crds/addonsconfiguration.yaml

- added rbac role
- bumped img version
- added ctrlInternalPort which fixes the chart

Align HB chart after introducing templating

---

OWNERS

- Fix issue, because of @michal-hudy who introduced that **bug** and I copied that 🤦 Probably next fixes will be applied.

Fix OWNERS file regex

---

internal/controller/common_test.go
pkg/apis/addons/v1alpha1/common.go

- Change reprocessRequest type to int

Change reprocessRequest type to int

---

charts/helm-broker/templates/deploy.yaml
charts/helm-broker/templates/svc.yaml
charts/helm-broker/values.yaml
cmd/controller/main.go
internal/broker/osbapi_test.go
internal/broker/server.go
internal/config/controller_config.go
pkg/health/health.go

- Implemented the same way for checking the health status of helm-broker and helm-controller.

Implement health checking for HelmBroker

---

charts/helm-broker/values.yaml
hack/ci/lib/deps_ver.sh
hack/ci/lib/utilities.sh
hack/ci/run-chart-test.sh
test/charts/helm_broker_test.go

- Apply minor changes to utilities.sh script

Apply minor changes to utilities.sh script

---

internal/controller/common.go
internal/controller/docs/cluster_provider.go
internal/controller/docs/provider.go

- Added waiter for DocsTopics and ClusterDocsTopics
- FIxed error message in case if there was something wrong with docsTopics 

Add waiter for DocsTopics

---

CODEOWNERS

- Add Maja and Alex as codeowners od the .md files in the `helm-broker` repo

Add Maja and Alex to CODEOWNERS

---

deploy/broker/Dockerfile
deploy/controller/Dockerfile
deploy/tests/Dockerfile
deploy/tools/Dockerfile

- use Alpine 3.10 instead of 3.8

Upgrade to alpine 3.10

---

CONTRIBUTING.md

Fix release3

---

internal/controller/addons_controller_test.go
internal/controller/cluster_addons_controller_test.go
internal/controller/common.go
internal/model.go
test/integration/integration_test.go
test/integration/suite_test.go

- process (Cluster)AddonsConfiguration with phase Pending
Fixes: https://github.com/kyma-project/helm-broker/issues/57

Process pending addons

---

internal/health/controller.go

- Removed clusterAddonConfiguration liveness

Remove clusterAddonConfiguration liveness

---

CODEOWNERS
OWNERS
charts/helm-broker/Chart.yaml

- Added myself to CODEOWNERS and all related files
[#418](https://github.com/kyma-project/community/issues/418)

Add member to codeowners

---

Makefile

- Fixed latest release process

Fix latest release

---

charts/helm-broker/values.yaml
cmd/controller/main.go
internal/config/config.go
internal/config/controller_config.go
internal/health/controller.go

- Removed hardcoded liveness probe's creation namespace - used release namespace instead

Remove hardcoded namespace name for liveness probe check

---

hack/examples/redis-instance-conflicting.yaml
internal/broker/fixture_test.go
internal/broker/osbapi_test.go
internal/broker/provision.go
internal/broker/provision_test.go
internal/model.go

- Added soft migration for parameters

Add soft migration for parameters

---

charts/helm-broker/templates/deploy.yaml
charts/helm-broker/values.yaml
cmd/broker/main.go
internal/broker/server.go
internal/config/config.go

Related to [#6579](https://github.com/kyma-project/kyma/issues/6579), all reasons are described [here](https://github.com/kyma-project/kyma/pull/6750)

Put metrics endpoint to separate server with own port

---

Gopkg.lock
Gopkg.toml
internal/broker/fixture_test.go
internal/broker/provision.go
internal/broker/provision_export_test.go
internal/controller/common.go

Related to [#6814](https://github.com/kyma-project/kyma/issues/6814)
Issue description is [here](https://github.com/kyma-project/kyma/issues/6814#issuecomment-572652068)

changing the way to generate a name for a release

---

Makefile
before-commit.sh
charts/helm-broker/ci/README.md
charts/helm-broker/ci/built-image-values.yaml
charts/helm-broker/templates/deploy.yaml
charts/helm-broker/templates/tests/test-addons-serving.yaml
charts/helm-broker/values.yaml
hack/build-binaries.sh
hack/ci/lib/utilities.sh
hack/ci/run-chart-test.sh

- Run chart testing always with image from pr
- kyma-project/kyma#6644

Run chart testing always with image from pr

---

docs/security.md

- Created security documentation

Create security documentation

---

Gopkg.lock
Gopkg.toml
internal/storage/testing/chart_test.go

Bump helm client

---

Gopkg.lock
Gopkg.toml

Bump gopkg yaml lib

---

Makefile
internal/helm/client.go
internal/storage/driver/etcd/entity_chart.go

- Use code straight from the h3 client
- Add nil pointer check when encoding chart

Fix OOM issue with helm 3 client

---

go.mod
internal/broker/deprovision.go
internal/broker/deprovision_test.go

- Example: https://github.com/helm/helm/blob/bb47286f09331271e88e6047c51fd6e0ea936506/pkg/action/upgrade.go#L167

Fix deprovisioning if release is not found

---

internal/broker/provision.go

- Improved error message when a user has no sufficient permissions to provision a service.
Before:
Now:
#102

Readable message when user has lack of permissions

---

internal/storage/driver/etcd/entity_instance.go
internal/storage/driver/etcd/entity_operation.go

- Register required gob interfaces in the constructor. As a result, we do not depend on other domains and assumption that the given type is already registered.
**Related issue:**
- https://github.com/kyma-project/helm-broker/issues/106

Register required gob interfaces in constructor

---

charts/helm-broker/values.yaml
docs/configuration.md
internal/config/controller_config.go
internal/controller/addons_controller.go
internal/controller/addons_controller_test.go
internal/controller/cluster_addons_controller.go
internal/controller/cluster_addons_controller_test.go
internal/controller/common.go
internal/controller/common_test.go
internal/controller/repository/repository.go
internal/controller/repository/repository_collection.go
internal/controller/setup.go
internal/health/controller.go
internal/model.go
pkg/apis/addons/v1alpha1/common.go
pkg/apis/addons/v1alpha1/reason.go
test/integration/integration_test.go
test/integration/suite_test.go

- reprocess (cluster)addonsconfiguration on fetching error
Related: https://github.tools.sap/kyma/backlog/issues/780

Reprocess Addons configuration on temporary error (for example network)

---

charts/helm-broker/values.yaml
deploy/controller/Dockerfile

Set versions in dockerfile

---

internal/health/controller.go

- Fix context error on liveness probe - using separate context for k8s API calls 
```
// For outgoing client requests, the context controls cancellation.
//
// For incoming server requests, the context is canceled when the
// client's connection closes, the request is canceled (with HTTP/2),
// or when the ServeHTTP method returns.
func (r *Request) Context() context.Context {
if r.ctx != nil {
return r.ctx
}
return context.Background()
}
```

Fix context error on liveness probe

---

CODEOWNERS

- Add crabtree and kjaksik as codeowners

Add crabtree and kjaksik as codeowners

---

deploy/controller/Dockerfile

Bump curl version in the Dockerfile

---

deploy/controller/Dockerfile

Bump external dependencies

---

deploy/controller/Dockerfile

- Bumped alpine version to 3.13 due to security reasons

Bump alpine version

---

charts/helm-broker/values.yaml
cmd/broker/main.go
cmd/controller/main.go
internal/controller/setup.go
internal/storage/storage.go

Fix containers startup

---

charts/helm-broker/values.yaml
internal/controller/broker/broker_facade.go
internal/controller/broker/cluster_broker_facade.go
internal/controller/broker_controller.go
internal/controller/cluster_broker_controller.go

- Fixed broker resources creation

Fix broker creation

---

charts/helm-broker/values.yaml
deploy/controller/Dockerfile

Bump base alpine

---

.github/pull-request-template.md
.github_changelog_generator
CODE_OF_CONDUCT.md
CONTRIBUTING.md
docs/development.md
docs/releasing.md

SAP is replacing insensitive terms (such as `master` / `slave`, `whitelist` / `blacklist`) with an inclusive language that helps to create a more inclusive workplace and ecosystem. To comply with this vision, we must adjust our documentation and correct the usage of these terms.
- Rename `master` references to `main`
https://github.com/kyma-project/community/issues/515

Remove insensitive terms

---

README.md
charts/helm-broker/README.md
docs/11-security.md

SAP is replacing insensitive terms (such as `master` / `slave`, `whitelist` / `blacklist`) with an inclusive language that helps to create a more inclusive workplace and ecosystem. To comply with this vision, we must adjust our documentation and correct the usage of these terms.
- Rename `master` references to `main`
https://github.com/kyma-project/community/issues/515

Change the remaining master references to main

---

charts/helm-broker/values.yaml
deploy/controller/Dockerfile

`alpine:3.13.3` has known security vulnerabilities
- Bumped base image in helm-controller to `alpine:3.13.5`

Bump alpine image in helm-controller to 3.13.5

---

deploy/controller/Dockerfile

- update python in the Dockerfile to 3.9.5-r1

Bump python version to 3.9.5-r1

---

charts/helm-broker/values.yaml
deploy/controller/Dockerfile

- Update dependencies in controller dockerfile

Update dependencies in controller dockerfile

---

deploy/controller/Dockerfile
hack/release/push_release.sh

- use non-deprecated auth
- upgrade Alpine
https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

Github: update deprecated authorization

---

deploy/controller/Dockerfile

- edit controller dockerfile so apk add targets higher git versions (>= 2.33.0-r0)

Edit apk add to target higher git versions

---

deploy/controller/Dockerfile

- addressing CVE-2021-3711, CVE-2021-3712

Bump base image in controller to alpine:3.14.2

---

charts/helm-broker/values.yaml

- bump img versions in values.yaml

Bump image versions

---

docs/01-installation.md
hack/run-dev-kind.sh

- Updating installation documentation
- Updating script that provides installation 

Updating installation docs and script

---

CODEOWNERS
internal/broker/server.go

Sanitize http resposne

---

internal/broker/server.go

- sanitize incoming parameters

Sanitize values provided by the user

---

charts/helm-broker/values.yaml
deploy/controller/Dockerfile
go.mod
go.sum

- bump alpine image version to 3.14.3 in helm-controller
- bump dependencies

Fix security vulnerabilities

---

deploy/controller/Dockerfile

bumping alpine image version to 3.15.0

Bump alpine image to 3.15.0

---

go.mod
go.sum

https://github.tools.sap/kyma/security-scans/issues/13317
https://github.tools.sap/kyma/security-scans/issues/13316
https://github.tools.sap/kyma/security-scans/issues/13313
https://github.tools.sap/kyma/security-scans/issues/13312
https://github.tools.sap/kyma/security-scans/issues/13314
https://github.tools.sap/kyma/security-scans/issues/13315

Whitesource fixes

---

charts/helm-broker/values.yaml
cmd/broker/main.go

- remove new line to trigger automatic creation of images

Bump images
